insert into cozinha (nome) values ('brasileira');
insert into cozinha (nome) values ('italiana');
insert into restaurante (nome, cozinha_id) values ('MC Donalds', 1);
insert into restaurante (nome, cozinha_id) values ('Pizzaria ABCFC', 2);
insert into estado (nome) values ('RN');
insert into estado (nome) values ('SP');
insert into estado (nome) values ('PE');
insert into cidade (nome,estado_id) values ('Natal', 1);
insert into cidade (nome,estado_id) values ('Macaíba', 1);
insert into cidade (nome,estado_id) values ('Recife', 3);